import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import Navbar from "@/components/Layouts/Navbar";
import 'react-toastify/dist/ReactToastify.css';
import SpinnerCard from "@/components/Global/Spinner";
import { Suspense } from "react";
import HydrationZustand from "@/components/Providers/HydrationZustand";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  metadataBase: new URL("http://localhost:3000"),
  title: "Social Media",
  description: "Generated by create next app",
  openGraph: {
    title: "Social Media",
    description: "Generated by create next app",
    url: "http://localhost:3000",
    siteName: "Code With Salim",
    images: [
      {
        url: "/oftto.png",
        alt: "Og Image Alt",
        width: 1200,
        height: 630,
      },
    ],
    locale: "en-US",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
        <HydrationZustand LoaderComponent={<SpinnerCard />}>
          <Navbar>
            {children}
          </Navbar>
        </HydrationZustand>
        </ChakraProvider>
      </body>
    </html>
  );
}
